### ISSUE TITLE
Should calling of sendMail creates mail for lastMail() access?

### ISSUE THREAD

**Issue by mirth** [LimeDeck/nodemailer-stub#1]
For now it doesn't create new in mail queue but i see `iwm.newMail` in `stubTransport.js`

**Comment by insanesvk** [comment]
Which version of nodemailer are you using?

**Comment by mirth** [comment]
I'm using 1.0.1.

**Comment by insanesvk** [comment]
Not the version of this package, the actual Nodemailer. Are you using 3.x or 4.x ?

**Comment by mirth** [comment]
nodemailer@1.11.0

**Comment by mirth** [comment]
It seems the problem was with the nodemailer package version.
